services:
  api:
    build:
      context: .  # La racine de backend-projectmanagement
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "4000:4000"  # Format correct : une liste de mappings
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=test
      - TEST_MONGO_URI=mongodb://testuser:testpass@172.16.1.235:27018/testdb?authSource=admin


  web:
    build:
      context: ../frontend/projectmanagement  # Chemin corrigé
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "5173:5173"  # Format correct
    volumes:
      - "../frontend/projectmanagement:/src"
      - "/src/node_modules"

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: projectmanagement
      MONGO_INITDB_ROOT_PASSWORD: project123
    volumes:
      - db-data:/data/db

  mongotest:  
    image: mongo
    container_name: mongo-test
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpass
    volumes:
      - mongo-test-data:/data/db

volumes:
  db-data: {}
  mongo-test-data: {}