services:
  api:
    build:
      context: .  # La racine de backend-projectmanagement
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "4000:4000"  # Format correct : une liste de mappings
    volumes:
      - ".:/app"
      - "/app/node_modules"

  web:
    build:
      context: ../FrontEnd-ProjectManagement/projectmanagement  # Chemin corrigé
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "5173:5173"  # Format correct
    volumes:
      - "../FrontEnd-ProjectManagement/projectmanagement:/src"
      - "/src/node_modules"
      # Supprime cette ligne si le dossier public n'existe pas dans projectmanagement :
      - "../FrontEnd-ProjectManagement/projectmanagement/public:/src/public"

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: projectmanagement
      MONGO_INITDB_ROOT_PASSWORD: project123
    volumes:
      - db-data:/data/db

  mongotest:  
    image: mongo
    container_name: mongo-test
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpass
    volumes:
      - mongo-test-data:/data/db

volumes:
  db-data: {}
  mongo-test-data: {}