services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "4000:4000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=test
      - TEST_MONGO_URI=mongodb://testuser:testpass@mongo-test:27017/testdb?authSource=admin
    depends_on:
      - mongo-test
  web:
    build:
      context: ../frontend/projectmanagement
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "5173:5173"
    volumes:
      - "../frontend/projectmanagement:/src"
      - "/src/node_modules"
      - "../frontend/projectmanagement/public:/src/public"
  mongo:
    image: mongo:4.4
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: projectmanagement
      MONGO_INITDB_ROOT_PASSWORD: project123
    volumes:
      - db-data:/data/db
  mongo-test:
    image: mongo:4.4
    container_name: mongo-test
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpass
    volumes:
      - mongo-test-data:/data/db
volumes:
  db-data: {}
  mongo-test-data: {}